name: Build Test App

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGE.md'
      - 'doc/*'
      - '.github/*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Npm Install
        run: |
          git config --global url."https://github.com".insteadOf ssh://git@github.com
          npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Stemstar-Desktop-win
          path: dist/Stemstar-Desktop*win.exe
          retention-days: 1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: Stemstar-Desktop-win-ia32
            path: dist/Stemstar-Desktop*ia32.exe
            retention-days: 1

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Stemstar-Desktop-win-x64
          path: dist/Stemstar-Desktop*x64.exe
          retention-days: 1

  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install python2.7
        run: |
          brew install pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: Npm Install
        run: |
          pip install setuptools
          npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          export PYTHON_PATH=$(pyenv root)/shims/python
          npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Stemstar-Desktop-darwin
          path: dist/Stemstar-Desktop*.dmg
          retention-days: 1

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Npm Install
        run: npm ci

      - name: Build Dist
        env:
          GA_ID: ${{ secrets.GA_ID }}
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=8192
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Stemstar-Desktop-linux
          path: dist/Stemstar-Desktop*.deb
          retention-days: 1
